version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: pip
    directory: /DIY/06-LG-Camera
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
