#!/data/data/com.termux/files/usr/bin/bash
clear
su -c "/data/adb/v60profiles/wrapper.sh all"
echo
echo "CPU MAX, GPU 670 MHz and maximum GPU bandwidth are active."
echo
read -r -p "Press Enter to close..."
